#!/usr/bin/env bash
#
# ai-harness — minimal sync CLI for the AI harness shared repo.
# v0 prototype. Single-file bash script.
#
# Requires: bash 3.2+, git, yq, and shasum or sha256sum.
# Install yq with: brew install yq (Mac) or your distro's package manager.
#
# Commands:
#   init    Create a starter .ai-harness.yml in the current directory
#   sync    Fetch bundles defined in config and write to .claude/managed/
#   check   Verify .claude/managed/ matches config + lock (exit non-zero on drift)
#
set -euo pipefail

CONFIG_FILE=".ai-harness.yml"
LOCK_FILE=".ai-harness.lock"
MANAGED_DIR=".claude/managed"

# Pick a hash command available on this system.
if command -v sha256sum >/dev/null 2>&1; then
  HASH_CMD="sha256sum"
elif command -v shasum >/dev/null 2>&1; then
  HASH_CMD="shasum -a 256"
else
  echo "Need either sha256sum or shasum installed." >&2
  exit 1
fi

require() {
  command -v "$1" >/dev/null 2>&1 || { echo "Missing dependency: $1" >&2; exit 1; }
}

usage() {
  cat <<EOF
ai-harness <command>

  init    Create a starter $CONFIG_FILE
  sync    Fetch bundles and write to $MANAGED_DIR
  check   Verify $MANAGED_DIR matches $LOCK_FILE (for CI)
EOF
}

hash_file() {
  $HASH_CMD "$1" | awk '{print $1}'
}

# ----------------------------------------------------------------------
# init
# ----------------------------------------------------------------------

cmd_init() {
  if [[ -f "$CONFIG_FILE" ]]; then
    echo "$CONFIG_FILE already exists." >&2
    exit 1
  fi
  cat > "$CONFIG_FILE" <<'EOF'
# AI harness configuration
# version: a git tag in the ai-harness repo (e.g. v1.0.0)
# repo:    SSH or HTTPS URL of the ai-harness repo
# bundles: list of folders to pull from the repo
version: v0.0.1
repo: git@bitbucket.org:YOUR_WORKSPACE/ai-harness.git
bundles:
  - shared
  - android/shared
EOF
  echo "Created $CONFIG_FILE. Edit it, then run: ai-harness sync"
}

# ----------------------------------------------------------------------
# shared helpers
# ----------------------------------------------------------------------

read_config() {
  require git
  require yq
  [[ -f "$CONFIG_FILE" ]] || { echo "No $CONFIG_FILE. Run: ai-harness init" >&2; exit 1; }
  VERSION=$(yq -r '.version' "$CONFIG_FILE")
  REPO=$(yq -r '.repo' "$CONFIG_FILE")
  BUNDLES=()
  while IFS= read -r line; do
    [[ -n "$line" ]] && BUNDLES+=("$line")
  done < <(yq -r '.bundles[]' "$CONFIG_FILE")
}

# Print a deterministic "files:" lock body for everything under $1.
generate_lock_for() {
  local dir="$1"
  echo "files:"
  while IFS= read -r -d '' file; do
    local rel="${file#$dir/}"
    local hash
    hash=$(hash_file "$file")
    printf '  - path: %s\n    sha256: %s\n' "$rel" "$hash"
  done < <(find "$dir" -type f -print0 | sort -z)
}

# ----------------------------------------------------------------------
# sync
# ----------------------------------------------------------------------

cmd_sync() {
  read_config

  local tmp
  tmp=$(mktemp -d -t ai-harness-XXXXXX)
  trap 'rm -rf "$tmp"' EXIT

  echo "Fetching $REPO at $VERSION..."
  git clone --quiet --depth 1 --branch "$VERSION" "$REPO" "$tmp/repo"

  rm -rf "$MANAGED_DIR"
  mkdir -p "$MANAGED_DIR"

  for bundle in "${BUNDLES[@]}"; do
    local src="$tmp/repo/$bundle"
    if [[ ! -d "$src" ]]; then
      echo "Bundle not found in repo at $VERSION: $bundle" >&2
      exit 1
    fi
    local dest="$MANAGED_DIR/$bundle"
    mkdir -p "$dest"
    cp -R "$src/." "$dest/"
  done

  {
    echo "# Generated by ai-harness. Do not edit."
    echo "version: $VERSION"
    echo "repo: $REPO"
    echo "bundles:"
    for b in "${BUNDLES[@]}"; do echo "  - $b"; done
    generate_lock_for "$MANAGED_DIR"
  } > "$LOCK_FILE"

  echo "Sync complete. Review with: git diff $MANAGED_DIR $LOCK_FILE"
}

# ----------------------------------------------------------------------
# check
# ----------------------------------------------------------------------

cmd_check() {
  read_config
  [[ -f "$LOCK_FILE" ]] || { echo "No $LOCK_FILE — run sync first" >&2; exit 1; }
  [[ -d "$MANAGED_DIR" ]] || { echo "No $MANAGED_DIR — run sync first" >&2; exit 1; }

  local current
  current=$(mktemp)
  trap 'rm -f "$current"' EXIT

  generate_lock_for "$MANAGED_DIR" > "$current"

  # Compare only the files: sections of the lock and the recomputed state.
  local locked_files current_files
  locked_files=$(awk '/^files:/{flag=1; next} /^[^ ]/{flag=0} flag' "$LOCK_FILE")
  current_files=$(awk '/^files:/{flag=1; next} /^[^ ]/{flag=0} flag' "$current")

  if [[ "$locked_files" != "$current_files" ]]; then
    echo "Drift detected: $MANAGED_DIR does not match $LOCK_FILE." >&2
    echo "Run 'ai-harness sync' to re-sync, or revert your local changes." >&2
    exit 1
  fi
  echo "OK — $MANAGED_DIR matches $LOCK_FILE."
}

# ----------------------------------------------------------------------
# entry point
# ----------------------------------------------------------------------

main() {
  case "${1:-help}" in
    init)  cmd_init ;;
    sync)  cmd_sync ;;
    check) cmd_check ;;
    help|--help|-h) usage ;;
    *) echo "Unknown command: ${1:-}" >&2; usage >&2; exit 1 ;;
  esac
}

main "$@"
